"""Add MoodboardNode

Revision ID: 057fd8ef0b46
Revises: 12667a641fb8
Create Date: 2026-04-16 14:05:41.696264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '057fd8ef0b46'
down_revision: Union[str, Sequence[str], None] = '12667a641fb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moodboard_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('moodboard_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['moodboard_id'], ['moodboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moodboard_nodes_moodboard_id'), 'moodboard_nodes', ['moodboard_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_moodboard_nodes_moodboard_id'), table_name='moodboard_nodes')
    op.drop_table('moodboard_nodes')
    # ### end Alembic commands ###
