"""Initial schema: Users, Moodboards, TryOnJobs

Revision ID: 12667a641fb8
Revises: 
Create Date: 2026-04-15 09:03:07.311478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12667a641fb8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('source_credit', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_garments_category'), 'garments', ['category'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('credits_remaining', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.Column('last_credit_refresh', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('moodboards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), server_default=sa.text("'Untitled'"), nullable=False),
    sa.Column('canvas_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moodboards_user_id'), 'moodboards', ['user_id'], unique=False)
    op.create_table('try_on_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('moodboard_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('replicate_prediction_id', sa.String(length=128), nullable=True),
    sa.Column('person_asset_url', sa.Text(), nullable=False),
    sa.Column('garment_asset_url', sa.Text(), nullable=False),
    sa.Column('result_asset_url', sa.Text(), nullable=True),
    sa.Column('intermediate_assets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('current_stage', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preprocessing_ms', sa.Integer(), nullable=True),
    sa.Column('inference_ms', sa.Integer(), nullable=True),
    sa.Column('postprocessing_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['moodboard_id'], ['moodboards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('replicate_prediction_id')
    )
    op.create_index(op.f('ix_try_on_jobs_moodboard_id'), 'try_on_jobs', ['moodboard_id'], unique=False)
    op.create_index(op.f('ix_try_on_jobs_user_id'), 'try_on_jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_try_on_jobs_user_id'), table_name='try_on_jobs')
    op.drop_index(op.f('ix_try_on_jobs_moodboard_id'), table_name='try_on_jobs')
    op.drop_table('try_on_jobs')
    op.drop_index(op.f('ix_moodboards_user_id'), table_name='moodboards')
    op.drop_table('moodboards')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_garments_category'), table_name='garments')
    op.drop_table('garments')
    # ### end Alembic commands ###
